 ---
title: "Getting Used to High Level Discomfort"
date: 2025-04-15T21:41:35-05:00
showtoc: false
Summary: The title might sound a bit odd, and perhaps you might have a completely different idea of what you might expect to read in this article than what is actually present here. I left out a summary on purpose to keep the title a little cryptic. What even is "High Level Discomfort"? 
---

The title might sound a bit odd, and perhaps you might have a completely different idea of what you might expect to read in this article than what is actually present here. I left out a summary on purpose to keep the title a little cryptic.

What even is "High Level Discomfort"? 

Am I talking about learning how to endure high levels of discomfort or pain to make the mind strong? Learning how to endure intense hardships? Learning how to sleep standing up? Getting used to sitting in 8 AM lectures?

Nope, nope, nope!

By "High Level", I am talking about high-level abstraction, specifically when it comes to building things. I don't know if this is a common or rare phenomenon, but for me personally, something like this ends up happening:

- I want to build something interesting.
- When I get to the building, it feels like all I am really doing is putting together components that people have already built for me.
- I am uncomfortable with this fact. I am uncomfortable with the fact that, had these other people not existed to build these high level components, I wouldn't be able to do anything about it. It bothers me.

Why does this bother me? After searching for an answer for a very long time, my best guess is that when I build something by just assembling existing parts, it doesn't really feel like "I" built it. And anything that "I" cannot build should not be an object of comfort; since if I lose it, I'll end up being uncomfortable without being able to do anything about it.

Let's take concrete examples to illustrate this point:

- If I cannot build a Neural Network from scratch, including its core parallel mathematical computation libraries, I shouldn't be comfortable using the high-level Numpy, PyTorch, and Tensorflow library functions.

- If I cannot build a game engine from scratch, I should not become too comfortable with the idea of using pre-built game engines such as Unity, Unreal Engine, and Godot.

- If I cannot build a computer from scratch, I should not become too comfortable purchasing computers, since if my ability to purchase computers and comptuer parts were taken away, I wouldn't be able to do a thing about it.

- If I cannot make bread from scratch, I should not become too comfortable with the idea of purchasing bread, since it could be taken away from me on any day.

- If I cannot farm wheat from scratch, I should not become comfortable with idea of purchasing wheat.


The last two or three (depending on your sympathy for this kind of philosophy) points probably sounded a bit odd. Why should you worry about not being able to purchase bread or wheat? Indeed, the more prosperous a society is, the less you have to worry about being able to purchase things. The more properous it is, the higher the level of abstraction you can obtain for your own building needs. But should you get comfortable with a society that is prosperous today but might not be so tomorrow?

Of course, we can take this to its logical extreme, and I'm sure many a philosopher has done just that. But here, I don't want to do that. Rather, I want to talk about something else: I actually don't get as uncomfortable with those last two points. Those were actually only placed there to make a point. Then, am I not being hypocritical? Why am I picking and choosing which high-level abstractions I am okay with and which ones I am not? There at least seems to be some metric being applied, which is a sort of statistical likelihood of being able to get the same high-level abstraction in an arbitrary point in time in the future, or at least my perceived likelihood of that.

Of course, as Carl Sagan famously said, "If you wish to make an apple pie from scratch, you must first invent the universe". Indeed, there is really no such thing as making anything "truly" from scratch. When making anything as a human, you must, at the very least, use the high level components provided by the universe to you on Earth. Moreover, even the greatest of minds such as Isaac Newton acknowledge that they are "standing on the shoulders of giants". One of the core reasons humans have achieved so much *is* the unabashed use of the high-level components created by their ancestors, whether literally or figuratively in terms of knowledge. Don't re-invent the wheel, as they say. So why the discomfort?

** Magic.

That's right, magic. I find magic uncomfortable. Though magic systems are cool to read about in books, the more opaque they are (so-called "soft" magic systems), the more uncomfortable they would actually feel to use. Not understanding where this seemingly brilliant power comes from means that I am the one being controlled by the power rather than the one controlling /it/. I am at the mercy of the power and its creator. If the power decides to disfunction one day, I won't be able to do a thing about it. If the creator of the power decides one day that I cannot use it, I won't be able to do a thing about it. When I see characters in fictional magical settings get arrogant about their powers, I always wonder: how would they react if the next day, magic just ceased to exist? Maybe I'll write a short story or book with this premise, but for now, it serves to illustrate the idea that if you don't understand how your tools work and how to construct them, you are simply borrowing them for the time being.

Of course, there is nothing wrong with using what is at your disposal to best achieve the task you want to achieve. I am no Luddite. However, what I /am/ wary about, is getting comfortable with the idea that these tools will always be around. I *still* find modern communication networks to be complete and utter magic. Even after learning about their inner-workings to some extent, I still feel like there is a whole sea of knowledge about them that I don't have. The idea that we can just send messages through the air, even after learning the theory behind it, feels like cheating. It doesn't feel like something that we should be able to do, and yet we can. I really don't know if I would be able to construct even one *tiny* component that goes in modern networks such as an ethernet cable. The best I might be able to do is write some of the higher level software that sits on top of the vast and incredibly complicated structure of hardware. Should I really be comfortable with the idea that modern communications networks will always be available then? Maybe, since that is all I have ever known, but maybe not, since they are a highly nontrivial invention that is the culmination of the work of millions of people over hundreds of years. It's not like growing a potato. 

I think the rigorous study of mathematics has deluded me into thinking that everything can be understood from the ground up. After all, I was able to take ten or twelve statements as assumptions and build centuries and centuries worth of mathematics just from that. And there, I felt like I truly *owned* my understanding of facts. When I understand a theorem of calculus, I am, if I wish to, break it down entirely in terms of ZFC. This cannot be said about the real, hard sciences, which typically always start with some high-level assumptions about reality (except some very specific parts of physics). 

So what is the resolution then? Do I keep struggling to accept the tools I am using every day? I haven't quite figured out a sophisticated solution to this yet, and I don't know if I ever will. For now, my plan is simple: use what is available while being prepared for the possibility that it won't be in the future. Do what the stoics did, try to live with the mindset that even if these tools are available, you don't *need* them. This is the only way to prevent an utter panic if such a situation does arise. At the same time, it is crucial to constantly learn and adapt to all the available high level components and tools at my disposal so that I don't drown in the pit that is ludditehood. 

