---
title: "A Physics View of Function Optimization"
date: 2025-01-21T21:39:20-06:00
Summary: An exploration of how the common problem of function optimization over $\mathbb{R}^d$ can be viewed through the lens of physics, and in particular, Hamiltonian mechanics. This perspective is taken by many modern papers on optimization algorithms, and none of them seem to go too deep into the motivations.
---

In my recent readings, I have encountered several papers that convert the usual [[https://optimization.cbe.cornell.edu/index.php?title=Momentum][momentum-based]] [[https://en.wikipedia.org/wiki/Mathematical_optimization][optimization]] algorithms such as [[https://pages.cs.wisc.edu/~brecht/cs726docs/HeavyBallLinear.pdf][Polyak's Heavy Ball Method]] or [[https://optimization.cbe.cornell.edu/index.php?title=Adam][Adam]] to their /continuous-time/ variants in order to perform some form of analysis on them.

Here, I would like to explore the broad notions used in these papers.

* Continuous Time Forms
One of the interesting notions in many of these papers is to look at the /continuous-time/ forms of momentum based optimizers. The main problem I tend to face is that these papers usually just don't explain how they arrived to a particular system of differential equations for the continuous time form of a particular optimizer. A friend of mine suggested that it could be just looking at the differential equations for which the optimizer update matches [[https://en.wikipedia.org/wiki/Euler_method][Euler's Method]] for solving ODEs. For example, the usual vanilla gradient descent rule is

$$x_{t^{(i + 1)}} = x_{t^{(i)}} - \eta \cdot \nabla f (x_{t^{(i)}})$$

where $f$ is the loss function and $\eta$ is some learning rate. If we instead let $\eta = t^{(i + 1)} - t^{(i)} = \Delta t$, we get

$$x_{t^{(i + 1)}} = x_{t^{(i)}} - \nabla f (x_{t^{(i)}}) \Delta t$$

which is indeed the recurrence relation of Euler's method for the differential equation

$$x' = -\nabla f(x)$$

The classic momentum update rule described by Polyak is given by

$$p_{t^{(i)}} = \beta \cdot p_{t^{(i - 1)}} - (1 - \beta)\nabla f(x_{t^{(i)}})$$

$$x_{t^{(i + 1)}} = x_{t^{(i)}} - \alpha \cdot p_{t^{(i)}}$$

We can try to write this as a /system/ of two differential equations. The first equation isn't yet in the typical Euler form, so we rewrite it as

$$p_{t^{(i)}} = p_{t^{(i - 1)}} + (\beta - 1)\cdot p_{t^{(i - 1)}} - (1 - \beta) \cdot \nabla f(x_{t^{(i)}})$$

Factoring out $(\beta - 1)$ from the last two terms, we get

$$p_{t^{(i)}} = p_{t^{(i - 1)}} + (\beta - 1) \cdot (p_{t^{(i - 1)}} + \nabla f(x_{t^{(i)}}))$$

Then if $\beta = \Delta t + 1$, we have the standard form of Euler's method for the differential equation

$$p' = p + \nabla f(x)$$

For the other equation, we have a simpler differential equation, $x' = -p$.

We can then put them together by replacing $p'$ with $-x''$, giving us

$$x'' = -p - \nabla f (x)$$

Since $-p = x'$,

$$x'' = -x' - \nabla f(x)$$

Though this still seems a bit odd and contrived to me, it does seem that the momentum optimizer is the correct Euler method reccurence for this system of differential equations, and should therefore work to find the true trajectory defined by the differential equations when $p + \nabla f(x)$ is Lipschitz. Of course, just because the approximation is correct doesn't mean that the trajectory is of any use. It must be shown that $x(t)$ converges a stationary point of the loss function $f$. 

* Hamiltonian Dynamics

The paper entitled [[https://arxiv.org/abs/1809.05042]["Hamiltonian Descent Methods"]] by Maddison et al. notes that this system mirrors a Hamiltonian dynamics system from physics, which is typically stated as

$$x'_t = \nabla_p \mathcal{H}(x_t, p_t) = \nabla k(p_t)$$

$$p'_t = -\nabla_x \mathcal{H}(x_t, p_t) = -\nabla f(x)$$

where $\mathcal{H}(x_t, p_t)$ is the total energy in the system as a function of the position and momentum, $k$ is the kinetic energy as a function of the momentum, and $f$ is the potential energy as a function of the position. If we let $k(p_t) = \langle p_t, p_t \rangle / 2$, the equations are nearly identical to the previously continuous time version of th e momentum optimizer (note that since I'm using the version where momentum is /subtracted/, the sign is flipped), with the caveat that the the second differential equation also has the term $p$, which the paper talks about as a "disspiation field" of the form $p'_t = -\gamma \cdot p_t$, thus giving us a final field $(x'_t, p'_t) = F(x_t, p_t) + G(x_t, p_t)$ where $F$ is the Hamiltonian field $(\nabla k (p_t), -\nabla f(x))$ and $G$ is the dissipation field $(0, -\gamma \cdot p_t)$. The paper calls this a "conformal" Hamiltonian field/system. It also allows for a notion of a more general conformal Hamiltonian system, where $k$ is allowed to be an arbitrary nonnegative convex function with $k(0) = 0$ and $\gamma > 0$. 

This poses the problem of optimization as a problem of computing the trajectory of a particle $x$ placed in a force field defined by the loss function $f$ starting at some position $x_0$ with some velocity $p_0$, where there also exists a dissipation force that scales with the particle's velocity and makes it an important factor in deciding where the particle will go next. The solutions to the system of differential equations remains in the set $\{(x, p)  : \mathcal{H}(x, p) = H_0\}$ for conservative forces $\nabla f$. However, when we add a disspitation force, such as the one defined by the momentum term in our optimizer, the total energy of the system decreases over time. 

A result from this paper is that given sufficiently nice conditions to the system, there exists a unique solution $(x_t, p_t)$ given initial conditions $(x_0, p_0)$ and that the position function $x$ converges to a stationary point of $f$.

** Conditions
The specific conditions for existence are as follows:

- $k$ is nonnegative and convex with $k(0) = 0$ (I stated this above as the domain of functions that $k$ can be chosen from).

- $\nabla f$ and $\nabla k$ are continuous. 

- $\mathcal{H}$ is /radially unbounded/: $\mathcal{H}(x, p) \to \infty$ as $||(x, p)||_{2} \to \infty$. This notation is a little unclear to me. The best guess I can make is that for any $\epsilon > 0$, there exists $\delta > 0$ such that for all $(x, p)$, $||(x, p)||_2 > \delta \implies \mathcal{H}(x, p) > \epsilon$.

For uniquness, the additional condition that $\nabla f$ and $\nabla k$ are continuously differentiable is imposed.

For convergence to a stationary point of $f$, given a solution $(x_t, p_t)$ to the system with initial conditions $(x_0, p_0) = (x, p)$, the following conditions are imposed:

- $f$ and $k$ are continuously differentiable
- $k$ is strictly convex with a minimum $k(0) = 0$
- $\mathcal{H}$ is radially unbounded
- $f$ is bounded bel, though it might not be so useful for those that are only really familiar with the mathematics of it. 

Given the above conditions, the paper shows that $||\nabla f(x_t)||_2 \to 0$.

Looking at this optimization problem from a physics perspective is perhaps insightful for people who have a strong understanding of and intuition for physics, though it might not be so useful for those that are only really familiar with the mathematics of it. 
